spring:
  profiles: docker

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    diskspace:
      enabled: true

app:
  product-service:
    host: product
    port: 8080
  review-service:
    host: review
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
